/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectuas;

/**
 *
 * @author LENOVO
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        thn1 = new javax.swing.JMenu();
        mn2010 = new javax.swing.JMenuItem();
        mn2015 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        thn = new javax.swing.JMenu();
        mn2009 = new javax.swing.JMenuItem();
        mn2014 = new javax.swing.JMenuItem();
        mn2019 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI DATA BPS PEMILU ");

        jLabel2.setText("14 DESEMBER 2022");

        thn1.setText("FILE");

        mn2010.setText("ABOUT");
        mn2010.setPreferredSize(new java.awt.Dimension(40, 22));
        mn2010.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn2010ActionPerformed(evt);
            }
        });
        thn1.add(mn2010);

        mn2015.setText("KELUAR");
        mn2015.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn2015ActionPerformed(evt);
            }
        });
        thn1.add(mn2015);

        jMenuBar1.add(thn1);

        jMenu1.setText("STATISTIK PEMILU");

        jMenu3.setText("DPD");

        jMenuItem3.setText("DKI JAKARTA");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("JAWA BARAT");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("JAWA TENGAH");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("JAWA TIMUR");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("BANTEN");
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenu4.setText("DPRD I");

        jMenuItem8.setText("KABUPATEN SERANG");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("KABUPATEN PANDEGLANG");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("KABUPATEN BOGOR");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("KABUPATEN GARUT");
        jMenu4.add(jMenuItem11);

        jMenu1.add(jMenu4);

        jMenu5.setText("DPRD II");

        jMenuItem1.setText("KOTA JAKARTA PUSAT");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("KOTA JAKARTA TIMUR");
        jMenu5.add(jMenuItem2);

        jMenuItem12.setText("KOTA JAKARTA BARAT");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("KOTA JAKARTA UTARA");
        jMenu5.add(jMenuItem13);

        jMenuItem14.setText("KOTA JAKARTA SELATAN");
        jMenu5.add(jMenuItem14);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        thn.setText("TAHUN ");

        mn2009.setText("2009");
        mn2009.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn2009ActionPerformed(evt);
            }
        });
        thn.add(mn2009);

        mn2014.setText("2014");
        mn2014.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn2014ActionPerformed(evt);
            }
        });
        thn.add(mn2014);

        mn2019.setText("2019");
        mn2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn2019ActionPerformed(evt);
            }
        });
        thn.add(mn2019);

        jMenuBar1.add(thn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(876, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn2009ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn2009ActionPerformed
        // TODO add your handling code here:
        CekData c = new CekData();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mn2009ActionPerformed

    private void mn2014ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn2014ActionPerformed
        // TODO add your handling code here:
        CekData c = new CekData();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mn2014ActionPerformed

    private void mn2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn2019ActionPerformed
        // TODO add your handling code here:
        CekData c = new CekData();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mn2019ActionPerformed

    private void mn2010ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn2010ActionPerformed
        new Login().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mn2010ActionPerformed

    private void mn2015ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn2015ActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_mn2015ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mn2009;
    private javax.swing.JMenuItem mn2010;
    private javax.swing.JMenuItem mn2014;
    private javax.swing.JMenuItem mn2015;
    private javax.swing.JMenuItem mn2019;
    private javax.swing.JMenu thn;
    private javax.swing.JMenu thn1;
    // End of variables declaration//GEN-END:variables
}
